# -*- coding: utf-8 -*-
"""3A-MONTESA-EXER1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M7Hhkle_zT3WSI-8A5bzprWg7-2wzv8F

#Exercises: Logic-Based Presentation

*This notebook contains Python Exercises.*

**Exercise 1: Propositional Logic in Python**

**Objectives:** Student will learn how to represent simple facts and rules using propositional logic and implement them in Python.
"""

raining = True
ground_wet = False
match_light = True

if raining:
  ground_wet = True

if ground_wet:
  match_light = False

if match_light:
  print("The match will light.")
else:
  print("The match will not light.")

"""Since it's raining (rain = True), the ground becomes wet (ground_wet = True), and the match won’t light (match_light = False). The output will be "The match will not light."

**Exercise 2: Predicate Logic Representation**

**Objective:**
Students will apply predicate logic to represent relationships between objects and
implement them in Python.
"""

def isHuman(name):
  return name == "Socrates"

def isMortal(name):
  if isHuman(name):
    return True
  return False

name = "Socrates"
if isMortal(name):
  print(f"{name} is mortal.")

else:
  print(f"{name} is not mortal.")

"""isHuman("Socrates") returns True, and because all humans are mortal, isMortal("Socrates") also returns True. Therefore, the output will be "Socrates is mortal."

**Exercise 3: Inference Techniques in Logic-Based Systems**

**Objective:** Students will develop an inference system to derive conclusions from premises using Python.
"""

def modus_ponens(facts, rules):
    new_facts = set(facts)
    conclusions = []

    for rule in rules:
        premise, conclusion = rule

        if premise in new_facts:
            if conclusion not in new_facts:
                new_facts.add(conclusion)
                conclusions.append(conclusion)

    return conclusions

facts = ["X"]

rules = [("X", "Y"),
         ("Y", "Z")]

conclusions = modus_ponens(facts, rules)

print("Inferred conclusions:", conclusions)

"""**Exercise 4: Exercise 4: Hands-on Lab - Implementing a Logic-Based Model in Python**

**Objective:**
Students will implement a logic-based system in Python that performs simple reasoning using propositional or predicate logic.


"""

john_hungry = True
john_eating = False

while john_hungry:
  if john_hungry:
      john_eating = True
      print("John is eating")

  if john_eating:
    john_hungry = False
    print("John will be no longer hungry.")

print("Reasoning process completed.")

"""**Explanation:**

**1.Initial state: **John starts as hungry (john_hungry = True).

**Rule 1:** If John is hungry, he will start eating (john_eating = True).

**Rule 2:** Once John eats, he is no longer hungry (john_hungry = False).

The loop simulates the reasoning process until John's hunger status changes.

*This output shows that John ate and is no longer hungry, following the logic of the rules.*

#Case Study Session

**Objective:** Analyze a real-world case study where logic-based models are used for decision-making
(e.g., in AI systems or expert systems).

Applying Logic-Based Models in Expert Systems *italicized text*

Expert systems use logical reasoning to solve problems. They have a knowledge base of facts and rules, and an inference engine that applies the rules to deduce new facts.

*How Logic is Used*

Expert systems use propositional logic and predicate logic:

 **Propositional logic** represents simple facts and rules using AND, OR, NOT. For example: "If raining AND cold, THEN risk of ice."

 **Predicate logic** represents complex relationships. For example: "All birds can fly." Uses predicates like "is a bird" and quantifiers like "all".

The inference engine applies logical rules to the knowledge base to derive new facts. Two common methods are:

1. **Forward chaining**: Start with known facts, apply rules to infer new facts until a conclusion. Good for prediction.

2. **Backward chaining**: Start with a hypothesis, work backwards to find supporting facts. Good for diagnosis.

*Advantages*

 **Transparency**: The rules are explicit and human-readable, so the reasoning is explainable.

 **Flexibility**: Can handle incomplete info using fuzzy logic. Knowledge base can be updated.

 **Reusability**: Knowledge base and inference engine can be reused across applications.

*Challenges*

 **Knowledge acquisition**: Populating the knowledge base is difficult and time-consuming.

 **Scalability**: Inference can be computationally expensive as knowledge grows.

 **Brittleness**: Can't handle situations outside predefined rules. Invalid inputs produce nonsense.

*Case Study: MYCIN*

MYCIN was an early expert system for diagnosing bacterial infections. Used forward chaining on a knowledge base of 600+ rules.

Represented knowledge using predicate logic. For example:

```
IF primary-bacteremia AND culture-site=blood
THEN high-suspicion(0.7) of bacteremic-infection
```

Demonstrated potential but also challenges like knowledge acquisition difficulty. As AI advanced, other approaches like neural networks became more prominent for diagnosis.

In summary, expert systems use logical reasoning but face challenges. They remain an important AI tool, often combined with machine learning.

**Assignment: Implement a Logic-Based Model in Python**

**Objective:**
Develop a more complex logic-based system in Python to model real-world scenarios.
"""

def evaluate_loan (credit_score, annual_income):
  if credit_score > 700 and annual_income > 50000:
    return "Loan approved."

  elif credit_score > 600 and annual_income > 30000:\
  return "Loan approved with conditions."

  else:
    return "Loan denied."

credit_score = int(input("Enter your credit score: "))
annual_income = float(input("Enter your annual salary: "))

loan_status = evaluate_loan(credit_score, annual_income)

print(loan_status)

"""This is a simple Loan Checker System I build that decides if a loan application shouold be approved based on the following rules.

Rule 1: If the applicant's credit score is above 700 and their annual income is above 50,000, approve the loan.

Rule 2: If the applicant's credit score is above 600 and their annual income is above 30,000, approve the loan with conditions.

Rule 3: If the applicant's credit score is below 600, deny the loan.
"""